using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace AeviMap
{
    public enum Thread2Function
    {
        THREAD2_DISABLED,

        THREAD2_LOADINGWALK,
        THREAD2_LOADINGWALKUP,
        THREAD2_LOADINGWALKDOWN,
        THREAD2_LOADINGWALKLEFT,
        THREAD2_LOADINGWALKRIGHT,

        THREAD2_AFTERLOADINGWALKUP,
        THREAD2_AFTERLOADINGWALKDOWN,
        THREAD2_AFTERLOADINGWALKLEFT,
        THREAD2_AFTERLOADINGWALKRIGHT,

        THREAD2_OPENDOOR,
        THREAD2_OPENDOORANIMATION,

        THREAD2_LOADINGSTAIRSUP,
        THREAD2_LOADINGSTAIRSUP_LEFT,
        THREAD2_LOADINGSTAIRSUP_RIGHT,
        THREAD2_LOADINGSTAIRSDOWN,
        THREAD2_LOADINGSTAIRSDOWN_LEFT,
        THREAD2_LOADINGSTAIRSDOWN_RIGHT,

        THREAD2_SCROLLCLOUDS,


        THREAD2_MAX
    }
}
